import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dbConfig from "./utlis/dbConfig";
import Slider from "./Slider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex ">
          <Slider />
          <div className="w-full flex">
            <div className="md:w-full h-[567px] px-[50px] pb-14 mt-10">
              {/* <div className="border  w-[600px] h-[400px]">{children}</div> */}
              <div>{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
